ad/urls.py
from django.urls import path
from . import views


app_name = 'ad'

urlpatterns = [
    path('' , views.post_ad_view , name='post_ad') , 
    ]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'

urlpatterns = [
    path('' , views.home , name='home') , 
    path('home/' , views.home , name='home') , 

]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    path('' , views.productlist , name='product_list') , 
    path('category/<slug:category_slug>' , views.productlist , name='product_list_category') , 
    path('department/<slug:department_slug>' , views.productlist , name='product_list_department') , 
    
    path('detail/<slug:product_slug>' , views.productdetail , name='product_detail'),
    
]

sell/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('home.urls' , namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls' , namespace='products')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('post/', include('ad.urls' , namespace='ad')),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from product.models import Product , Category,Department
# Create your views here.

def home(request):
    
    all_category = Category.objects.all() 
    all_department = Department.objects.all() 
    
    products = Product.objects.all()
    latest_products = Product.objects.order_by("-created")[:4]
    template = 'home.html'
    context = { 'all_category' : all_category  ,'products' : products, 'all_department':all_department, 'latest_products' :latest_products}

    return render(request , template , context)

home/templates/home.html
{% extends 'base.html' %}

{% block body %}
	

<body>

	




		<!-- content-starts-here -->
		<div class="content">
			<div class="categories_new">
				<div class="container">
					<div class="trend-ads">
						<h2>Browse By Categories</h2>
					</div>
					
					{% for category in all_category %}
												
					<div class="col-md-2 focus-grid">
						<a href="{% url 'product:product_list_category' category.slug  %}">
							<div class="focus-border">
								<div class="focus-layout">
									<div class="focus-image"> <img src="{{category.image.url}}" /></div>
									<h4 class="clrchg">{{category}}</h4>
								</div>
							</div>
						</a>
					</div>

					{% endfor %}

					<div class="clearfix"></div>
				</div>
			</div>

			<div class="content">
				<div class="categories_new">
					<div class="container">
						<div class="trend-ads">
							<h2>Browse By Department</h2>
						</div>
						
						{% for department in all_department %}
													
						<div class="col-md-2 focus-grid">
							<a href="{% url 'product:product_list_department' department.slug  %}">
								<div class="focus-border">
									<div class="focus-layout">
										<div class="focus-image"> <img src="{{ department.image.url }}" /></div>
										<h4 class="clrchg">{{department}}</h4>
									</div>
								</div>
							</a>
						</div>
	
						{% endfor %}
	
						<div class="clearfix"></div>
					</div>
				</div>
			












			<div class="trending-ads">
				<div class="container">
				<!-- slider -->
				
			</div>
			<!-- //slider -->				
			</div>
			<div class="mobile-app">
				<div class="container">
					<div class="col-md-5 app-left">
						<a href="mobileapp.html"><img src="images/app.png" alt=""></a>
					</div>
					<div class="col-md-7 app-right">
						<h3>Resale App is the <span>Easiest</span> way for Selling and buying second-hand goods</h3>
						<p>                                                                                                                                                                                </p>
						<div class="app-buttons">
							<div class="app-button">
								<a href="#"><img src="images/1.png" alt=""></a>
							</div>
							<div class="app-button">
								<a href="#"><img src="images/2.png" alt=""></a>
							</div>
							<div class="clearfix"> </div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>


		<!--//brands-->
<!-- new -->
	<div class="newproducts-w3agile">
		<div class="container">
			
			<h3>Recently Added</h3>
				<div class="agile_top_brands_grids">
					
					{% for product in latest_products%}
					<div class="col-md-3 top_brand_left-1">
						<div class="hover14 column">
							<div class="agile_top_brand_left_grid">
								<div class="agile_top_brand_left_grid_pos">
									<img src="{{product.image.url}}" alt=" " class="img-responsive">
								</div>
								<div class="agile_top_brand_left_grid1">
									<figure>
										<div class="snipcart-item block">
											<div class="snipcart-thumb">
												<a href="{% url 'products:product_detail' product.slug %}"><img title=" " alt=" " src="{{product.image.url}}"></a>		
												<p> {{product.name}}    </p>
												
								
												
												<!-- <div class="stars">
													<i  aria-hidden="true"></i>
													<i  aria-hidden="true"></i>
													<i  aria-hidden="true"></i>
													<i  aria-hidden="true"></i>
													<i class="fa fa-star " aria-hidden="true"></i>
												</div> -->
													<h4>{{product.price}} <span>{{product.original_price}}</span></h4>
											</div>
											<div class="snipcart-details top_brand_home_details">
												<form action="{% url 'products:product_detail' product.slug %}" method="post">
													{% csrf_token %}
													<fieldset>
														<!-- <input type="hidden" name="cmd" value="_cart">
														<input type="hidden" name="add" value="1">
														<input type="hidden" name="business" value=" ">
														<input type="hidden" name="item_name" value="Fortune Sunflower Oil">
														<input type="hidden" name="amount" value="35.99">
														<input type="hidden" name="discount_amount" value="1.00">
														<input type="hidden" name="currency_code" value="USD">
														<input type="hidden" name="return" value=" ">
														<input type="hidden" name="cancel_return" value=" "> -->
														<input type="submit" name="submit" value="Details"   class="button">
													</fieldset>
												</form>
											</div>
										</div>
									</figure>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
					
					
					
						<div class="clearfix"> </div>
				</div>
		</div>
	</div>












		<!--footer section start-->		
		<footer>
			<div class="footer-top">
				<div class="container">
					<div class="foo-grids">
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Who We Are</h4>
							<!-- <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
							<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p> -->
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Help</h4>
							<ul>
								<!-- <li><a href="howitworks.html">How it Works</a></li>						
								<li><a href="sitemap.html">Sitemap</a></li>
								<li><a href="faq.html">Faq</a></li>
								<li><a href="feedback.html">Feedback</a></li>
								<li><a href="contact.html">Contact</a></li>
								<li><a href="typography.html">Shortcodes</a></li> -->
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Information</h4>
							<ul>
								<!-- <li><a href="regions.html">Locations Map</a></li>	
								<li><a href="terms.html">Terms of Use</a></li>
								<li><a href="popular-search.html">Popular searches</a></li>	
								<li><a href="privacy.html">Privacy Policy</a></li>	 -->
							</ul>
						</div>
						<div class="col-md-3 footer-grid">
							<h4 class="footer-head">Contact Us</h4>
							<span class="hq">Our headquarters</span>
							<!-- <address>
								<ul class="location">
									<li><span class="glyphicon glyphicon-map-marker"></span></li>
									<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-earphone"></span></li>
									<li>+0 561 111 235</li>
									<div class="clearfix"></div>
								</ul>	
								<ul class="location">
									<li><span class="glyphicon glyphicon-envelope"></span></li>
									<li><a href="mailto:info@example.com">mail@example.com</a></li>
									<div class="clearfix"></div>
								</ul>						
							</address> -->
						</div>
						<div class="clearfix"></div>
					</div>						
				</div>	
			</div>	
			<div class="footer-bottom text-center">
			<div class="container">
				<div class="footer-logo">
					<a href="index.html"><span>Re</span>sale</a>
				</div>
				<div class="footer-social-icons">
					<ul>
						<li><a class="facebook" href="#"><span>Facebook</span></a></li>
						<li><a class="twitter" href="#"><span>Twitter</span></a></li>
						<li><a class="flickr" href="#"><span>Flickr</span></a></li>
						<li><a class="googleplus" href="#"><span>Google+</span></a></li>
						<li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
					</ul>
				</div>
				<div class="copyrights">
					<p> © 2016 Resale. All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
		</footer>
        <!--footer section end-->
</body>

{% endblock body %}