accounts/urls.py
from django.urls import path , include
from . views import register
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/' , register , name='register') , 
    path('profile/',views.profile_detail , name='profile'),
    path('delete/<int:pk>/', views.product_delete, name='product_delete'),
    path('profile/ads',views.profile_ad_detail , name='profile_ad'),
    path('profile/edit',views.profile_edit , name='profile_edit'),
    path('chat/', include('chat.urls' , namespace='accounts')),
    # path('password_change/' , auth_views.PasswordChangeView.as_view() , name='password_change') , 
    # path('password_change/done/' , auth_views.PasswordChangeDoneView.as_view() , name='password_change_done') , 
    # path('password_reset/' , auth_views.PasswordResetView.as_view() , name='password_reset') , 
    # path('password_reset/done/' , auth_views.PasswordResetDoneView.as_view() , name='password_reset_done') , 
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']

]

ad/urls.py
from django.urls import path
from . import views


app_name = 'ad'

urlpatterns = [
    path('' , views.post_ad_view , name='post_ad') , 
    ]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    path('' , views.productlist , name='product_list') , 
    path('category/<slug:category_slug>' , views.productlist , name='product_list_category') , 
    path('department/<slug:department_slug>' , views.productlist , name='product_list_department') , 
    
    path('detail/<slug:product_slug>' , views.productdetail , name='product_detail'),
    
]

sell/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('home.urls' , namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls' , namespace='products')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('post/', include('ad.urls' , namespace='ad')),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class user_profile(models.Model):
    user = models.OneToOneField(User, null = True, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=25 ,  null=True,blank=False,unique=True)



    def __str__(self):
        return self.user.username
    
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            user_profile.objects.create(user=instance)
        instance.user_profile.save()        

    

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import user_profile

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['first_name' , 'last_name' ,'username' , 'email' , 'password' ]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = user_profile
        fields = ['phone_number']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = user_profile
        fields = ['phone_number']

accounts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .forms import UserForm , UserProfileForm,UserEditForm,ProfileEditForm
from .models import user_profile
from django.contrib.auth import authenticate, login
from product.models import Product
# Create your views here.


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('/accounts/login')
        

    else:
        user_form = UserForm()
        profile_form = UserProfileForm( )
    context = {'user_form' : user_form,
              'profile_form': profile_form}

    return render(request , 'registration/register.html' , context)



def profile_detail(request):
    # profile = user_profile.objects.get(user=request.user)
    ad_list = Product.objects.filter(owner = request.user)
    profile =None
    
    
    return render(request,'accounts/profile.html',{'profile': profile,  'ad_list':ad_list})


def profile_ad_detail(request):
    # profile = user_profile.objects.get(user=request.user)
    ad_list = Product.objects.filter(owner = request.user)
    
    
    
    return render(request,'accounts/profile_ad.html',{'ad_list':ad_list})



def profile_edit(request):
    profile = user_profile.objects.get(user=request.user)
    if request.method=='POST':
        userform = UserEditForm(request.POST , instance=request.user)
        profileform = ProfileEditForm(request.POST , instance=profile)
        
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myform = profileform.save(commit=False)
            myform.user = request.user
            myform.save()
           
            return redirect('/accounts/profile')

    else:
        userform = UserEditForm(instance=request.user)
        profileform = ProfileEditForm(instance=profile)

    return render(request,'accounts/edit_profile.html',{
        'userform' : userform,
        'edit_profile' : profileform
    })


def product_delete(request , pk):
    product = get_object_or_404(Product , pk = pk)
    
    if request.method== 'POST':
        product.delete()
        return redirect('/')
    
    return render(request,'accounts/profile.html' )


    

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}

{% load bootstrap4 %}
{% block body %}

<!-- Submit Ad -->
<div class="submit-ad main-grid-border">
    <div class="container">
        <h2 class="head">Edit Profile</h2>
        <div class="post-ad-form">
            <form method="post"">
                {% csrf_token %}
                {% bootstrap_form userform %}
                <!-- {% bootstrap_form edit_profile %} -->
                {% buttons %}
                <button type="submit" class="btn btn-primary ">Save Changes</button>
                {% endbuttons %}
                <div class="clearfix"></div>
            </form>

        </div>
    </div>
</div>
</div>
<!-- // Submit Ad -->
{% endblock body %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}


{% block body %}

<!-- Submit Ad -->

<div class="navigation-agileits">
    <div class="container">
        <nav class="navbar-profile navbar-default-profile">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header nav_2">
                            <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div> 
                        <div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
                            <ul class="nav navbar-nav-profile">
                                
                                <!-- Mega Menu -->
                             
                                <li><a href="{% url 'accounts:profile_ad' %}">Your Ads</a></li>
                                <li><a href="{% url 'accounts:profile_edit' %}">Change Profile</a></li>
                                <li><a href="">Chat</a></li>
                                <li><a href="contact.html"></a></li>
                            </ul>
                        </div>
                        </nav>
        </div>
    </div>


<div class="submit-ad main-grid-border">
    <div class="container">
        <h2 class="head">Welcome {{user}} </h2>
        <!-- <div class="post-ad-form">
            <h3>{{profile}}</h3>
            <div>
                
            </div>
        </div> -->
        
        {% block body_ad %}
        {% endblock body_ad %}
       
    
          
    
        
    </div>
</div>
</div>
<!-- // Submit Ad -->
{% endblock body %}
-------------

accounts/templates/accounts/profile_ad.html
{% extends "accounts/profile.html" %}
{% load static %}
{% load bootstrap4 %}



{% block body_ad %}
    
   


    <div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
        <div>
                            <div id="container">

            <div class="clearfix"></div>
            <h2 class="head">Your ads </h2>
        <ul class="list">
            
            {% for product in ad_list %}
                <a href="{% url 'products:product_detail' product.slug %}">
                    <li>
                    <img src="{{product.image.url}}" title="" alt="" />
                    <section class="list-left">
                    <h5 class="title">{{product.name}}</h5>
                    <span class="adprice">₹ {{product.price}}</span>
                    <p class="catpath">Mobile Phones » {{product.brand}}</p>
                    </section>
                    <section class="list-right">
                    <span class="date">Date, {{product.created}}</span>
                    
                    
                    <form action="{% url 'accounts:product_delete' product.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" value="Delete">
                    </form> 
                    </section>
                    
                    <div class="clearfix"></div>
                    </li> 
                </a>
            {% endfor %}
        </ul>
    </div>
        </div>
    </div>
    

 {% endblock body_ad %}