ad/urls.py
from django.urls import path
from . import views


app_name = 'ad'

urlpatterns = [
    path('' , views.post_ad_view , name='post_ad') , 
    ]

product/urls.py
from django.urls import path
from . import views


app_name = 'product'

urlpatterns = [
    path('' , views.productlist , name='product_list') , 
    path('category/<slug:category_slug>' , views.productlist , name='product_list_category') , 
    path('department/<slug:department_slug>' , views.productlist , name='product_list_department') , 
    
    path('detail/<slug:product_slug>' , views.productdetail , name='product_detail'),
    
]

sell/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('home.urls' , namespace='home')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('product.urls' , namespace='products')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
    path('post/', include('ad.urls' , namespace='ad')),



]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from .choices import *
# Create your models here.



class Product(models.Model):

    CONDITION_TYPE = (
        ("New" , "New") ,
        ("Used" , "Used")
    )

    ## contain all the products informations
    category = models.ForeignKey('Category' , on_delete=models.SET_NULL , null=True)
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User , on_delete=models.CASCADE)
    department = models.ForeignKey('Department' , on_delete=models.SET_NULL , null=True)
    description = models.TextField(max_length=500)
    condition = models.CharField(max_length=100 , choices=CONDITION_TYPE)
    
    contact_number = models.CharField(max_length=10 ,  null=True,blank=False)
    original_price = models.DecimalField(max_digits=10,decimal_places=2)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    image = models.ImageField(upload_to='main_product/' ,  blank = True,null=True)
    created = models.DateTimeField(default=timezone.now)




    slug = models.SlugField(blank=True  , null=True)
    
    def save(self , *args , **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Product , self).save(*args , **kwargs)


    def __str__(self):
        return self.name



class ProductImages(models.Model):
    product = models.ForeignKey(Product , on_delete=models.CASCADE,default=None)
    image = models.ImageField(upload_to='products/' , blank=True , null=True)

    def __str__(self):
        return self.product.name

    class Meta:
        verbose_name = 'Product Image'
        verbose_name_plural = 'Product Images'






class Category(models.Model):
    ## for product category
    category_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category/' , blank=True , null=True)

    slug = models.SlugField(blank=True  , null=True)


    def save(self , *args , **kwargs):
        if not self.slug and self.category_name :
            self.slug = slugify(self.category_name)
        super(Category , self).save(*args , **kwargs)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.category_name


class Department(models.Model):
    ## for product category
    department_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='department/' , blank=True , null=True)

    slug = models.SlugField(blank=True  , null=True)


    def save(self , *args , **kwargs):
        if not self.slug and self.department_name :
            self.slug = slugify(self.department_name)
        super(Department , self).save(*args , **kwargs)

    class Meta:
        verbose_name = 'department'
        verbose_name_plural = 'departments'

    def __str__(self):
        return self.department_name

product/views.py
from django.shortcuts import render
from .models import Product , ProductImages , Category,Department
from django.core.paginator import Paginator
from django.db.models import Count
from django.db.models import Q
from django.shortcuts import get_object_or_404
# Create your views here.


def productlist(request , category_slug=None ,department_slug=None):
    category = None
    productlist = Product.objects.all()
    department= None
    categorylist = Category.objects.annotate(total_products=Count('product'))
    departmentlist = Department.objects.annotate(total_products=Count('product'))
    latest_products = Product.objects.order_by("-created")[:3]

    if category_slug :
        category = get_object_or_404(Category ,slug=category_slug)
        productlist = productlist.filter(category=category)
    elif department_slug :
        department = get_object_or_404(Department ,slug=department_slug)
        productlist = productlist.filter(department=department)
    
   

    search_query = request.GET.get('q')
    if search_query :
        productlist = productlist.filter(
            Q(name__icontains = search_query) |
            Q(description__icontains = search_query)|
            Q(condition__icontains = search_query)|
           
            Q(category__category_name__icontains = search_query) 
        )

    paginator = Paginator(productlist, 20) # Show 25 contacts per page
    page = request.GET.get('page')
    productlist = paginator.get_page(page)
    template = 'Product/product_list.html'

    context = {'product_list' : productlist , 'category_list' : categorylist ,'category' : category , 'departmentlist' : departmentlist ,'department' : department, 'latest_products':latest_products}
    return render(request , template , context)

# def productlist(request , category_slug=None , department_slug=None):
#     category = None
#     department = None
#     productlist = Product.objects.all()
#     categorylist = Category.objects.annotate(total_products=Count('product'))
#     departmentlist = Department.objects.annotate(total_products=Count('product'))
    

#     if category_slug :
#         category = get_object_or_404(Category ,slug=category_slug)
#         productlist = productlist.filter(category=category)
    
#     if department_slug :
#         department = get_object_or_404(Department ,slug=department_slug)
#         productlist = productlist.filter(department=department)

#     search_query = request.GET.get('q')
#     if search_query :
#         productlist = productlist.filter(
#             Q(name__icontains = search_query) |
#             Q(description__icontains = search_query)|
#             Q(condition__icontains = search_query)|
           
#             Q(category__category_name__icontains = search_query) 
#         )

#     paginator = Paginator(productlist, 20) # Show 25 contacts per page
#     page = request.GET.get('page')
#     productlist = paginator.get_page(page)
#     template = 'Product/product_list.html'

#     context = {'product_list' : productlist , 'category_list' : categorylist ,'category' : category, 'department_list' : departmentlist ,'department' : department }
#     return render(request , template , context)





def productdetail(request , product_slug):
    
    productdetail = Product.objects.get(slug=product_slug)
    productimages = ProductImages.objects.filter(product=productdetail)
    template = 'Product/product_detail.html'
    context = {'product_detail' : productdetail , 'product_images' : productimages}
    return render(request , template , context)

product/templates/Product/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
	<!--single-page-->
	<div class="single-page main-grid-border">
		<div class="container">
			<ol class="breadcrumb" style="margin-bottom: 5px;">
				<li><a href="/">Home</a></li>
				<li><a href="{% url 'products:product_list' %}">All Ads</a></li>
				<li class="active">Mobile Phone</li>
			</ol>
			<div class="product-desc">
				<div class="col-md-7 product-view">
					<h2>{{product_detail.name}}</h2>
					<p>  Added at {{product_detail.created}}</p>
					<div class="flexslider">
						<ul class="slides">
                            <li data-thumb="{{product_detail.image.url}}">
								<img src="{{product_detail.image.url}}" />
							</li>
                            {% for image in product_images %}
                                                        
                                <li data-thumb="{{image.image.url}}">
                                    <img src="{{image.image.url}}" />
                                </li>

                            {% endfor %}
						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						
						<h4>Views : <strong>150</strong></h4>
						<p><strong>Summary</strong> {{product_detail.description}}</p>
					
					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">₹ {{product_detail.price}}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{product_detail.condition}}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>{{product_detail.category}}</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						<p><i class="glyphicon glyphicon-earphone"></i>{{ product_detail.contact_number }}</p>
						<br><a href="http://127.0.0.1:8000/accounts/chat/chatwith{{product_detail.owner}}/?username={{user.username}}"><button id="btn1" type="button"><b>Buy</b></button></a>
					</div>
						<!-- <div class="tips">
						<h4>Safety Tips for Buyers</h4>
							<ol>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
							</ol>
						</div> -->
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->

{% endblock body %}

product/templates/Product/product_list.html
{% extends 'base.html' %}

{% block body %}
  
	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">
			<div class="select-box">
				<div class="browse-category ads-list">
					<label>Browse Categories</label>
					<select class="selectpicker show-tick" data-live-search="true">
					  
					{% for category in category_list %}
					<option data-tokens={{category}}> {{ category }}</option>
					{% endfor %}
					  
					</select>
				</div>
				<div class="search-product ads-list">
					<label>Search for a specific product</label>
					<div class="search">
						<div id="custom-search-input">
						<div class="input-group">
							<input type="text" class="form-control input-lg" placeholder="search" />
							<span class="input-group-btn">
								<button class="btn btn-info btn-lg" type="button">
									<i class="glyphicon glyphicon-search"></i>
								</button>
							</span>
						</div>
					</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="all-categories">
				<h3> Select your category and find the perfect ad</h3>
				<ul class="all-cat-list">
                    
                    {% for category in category_list %}
					    <li><a href="{% url 'products:product_list_category' category.slug  %}">{{category}} <span class="num-of-ads">({{category.total_products}})</span></a></li>
                    {% endfor %}
				</ul>
			</div>
			<ol class="breadcrumb" style="margin-bottom: 5px;">
			  <li><a href="/">Home</a></li>
              <li class="active"> <a href="{% url 'products:product_list' %}"> All Ads </a></li>
              {% if category %}
              <li class="active">{{category}}</li>
              {% endif %}
			  
			</ol>
			<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
					<h3 class="sear-head">Search</h3>
					<form method="GET" action="{% url 'products:product_list' %}">
						<input type="text" placeholder="Product name..." name="q" required="">
						<input type="submit" value=" ">
					</form>
				</div>
				
				<div class="featured-ads">
					<h2 class="sear-head fer">Featured Ads</h2>
					{% for var in latest_products %}
					<div class="featured-ad">
						<a href="{% url 'products:product_detail' var.slug %}">
							<div class="featured-ad-left">
								<img src="{{ var.image.url }}" title="ad image" alt="" />
							</div>
							<div class="featured-ad-right">
								<h4>{{ var.description|truncatechars:50 }}</h4>
								<p>₹ {{ var.price  }}</p>
							</div>
							<div class="clearfix"></div>
						</a>
					</div>
					{% endfor %}
					
					<div class="clearfix"></div>
				</div>
				</div>
				<div class="ads-display col-md-9">
					<div class="wrapper">					
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
												<div id="container">

								<div class="clearfix"></div>
							<ul class="list">
                                
                                {% for product in product_list %}
                                    <a href="{% url 'products:product_detail' product.slug %}">
                                        <li>
                                        <img src="{{product.image.url}}" title="" alt="" />
                                        <section class="list-left">
                                        <h5 class="title">{{product.name}}</h5>
                                        <span class="adprice">₹ {{product.price}}</span>
                                        
                                        </section>
                                        <section class="list-right">
                                        <span class="date">Date, {{product.created}}</span>
                                        <span class="cityname">{{product.contact_number}}</span>
                                        </section>
                                        <div class="clearfix"></div>
                                        </li> 
                                    </a>
                                {% endfor %}
							</ul>
						</div>
							</div>
                        </div>
                        
                        {% if product_list.has_other_pages %}
                          
                            <ul class="pagination pagination-sm">
                                {% if product_list.has_previous %}
                                    <li><a href="?page={{ product_list.previous_page_number }}">Prev</a></li>
                                {% else %}
                                    <li class="disabled"></li>
                                {% endif %}
                                    
                                {% for pages in product_list.paginator.page_range %}
                                    {% if product_list.number == pages %}
                                        <li><a href="#">{{pages}}</a></li>
                                    {% else %}
                                        <li><a href="?page={{pages}}">{{pages}}</a></li>
                                    {% endif %}
                                    
                                {% endfor %}
                                    
                                
                                {% if product_list.has_next %}
                                    <li><a href="?page={{ product_list.next_page_number }}">Next</a></li>
                                {% else %}
                                    <li class="disabled"></li>
                                {% endif %}
                                   
                            </ul>

                        {% endif %}
					  </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>	
	</div>
    <!-- // Products -->
    
{% endblock body %}